### PR TITLE
Solutions

### PR DESCRIPTION
**Pull request by animusblue**
Kyle Smith
616-212-1569
ksmith.developer@gmail.com

### CODE REVIEW

**Comment by maluberian** [comment]
got it

**Comment by maluberian** [comment]
Challenge 1 is not correct. To give you a hint: 2 is a prime number and 2 % 2 == 0.

**Comment by maluberian** [comment]
Challenge 2 is correct!

**Comment by maluberian** [comment]
I am getting a NullReferenceError in challenge #3. Note that we are running a file for testing that is not the same as the example you were given.

>	challenge3.exe!challenge3.Program.FindLetter(char code, challenge3.Program.Node tree) Line 13	C#

**Comment by maluberian** [comment]
As of now, you have 2 entries (for #2). You can fix #1 and #3 and update this PR if you wish to get additional entries.

**Comment by animusblue** [comment]
Alright. They should be good now. I used the referenced map in solution 3 for the tree so if it can't find a match in the tree then it'll show #

**Comment by maluberian** [comment]
Congratulations on fixing challenge #1! Unfortunately, challenge #3 is still not correct. I see your #'s and see all of the letters of the message but not all the content of the message (hint: what about puntucation?). As of now, you have three entries in the drawing! Thanks for your entries.

**Pull request closed without merging**
