### PR TITLE
Challenges

### PR DESCRIPTION
**Pull request by aliitani**
Name: Ali Itani
Mobile: 269 370 1182
Email: aliitani0@gmail.com

### CODE REVIEW

**Comment by mnishizawa** [comment]
Thanks for your submission.  Challenge 1 has been verified so you currently have 1 entry.  For challenge 2 I need you to accept a file name as an input argument.  I can't modify your code to specify the file.

If you would like to make that change and/or finish the 3rd challenge today you are welcome to do that, just remember that they need to be completed by 3:00 pm today in order to be counted.

**Comment by mnishizawa** [comment]
Compile error: 

javac Challenge2.java                                                                                     
Challenge2.java:7: error: '{' expected
public class Challenge2 throws IOException, FileNotFoundException {
                       ^
1 error

**Comment by mnishizawa** [comment]
Still doesn't compile.  Does it compile and execute for you?

**Comment by aliitani** [comment]
Yeah, by giving the file path it compiles and executes fine for me.

**Comment by mnishizawa** [comment]
What version of Java are you using?  Adding a throws clause on a class is not spec.

**Pull request closed without merging**
