### PR TITLE
Aaron Day's Entries

### PR DESCRIPTION
**Pull request by crazydays**
Solutions for challenge 1 and challenge 2 written in bash.  They work on OSX, but ought to also work on linux.

### CODE REVIEW

**Comment by mnishizawa** [comment]
Thanks for your submission.  Your solutions for challenge 1 and 2 have been verified.  You have 3 entries to the drawing.  If you would like to finish the 3rd challenge you are welcome to do so as long as it is in by the deadline.  

If you haven't done so already, make sure to stop by the Bravo LT table tomorrow and introduce yourself. We look forward to seeing you there!

**Comment by mnishizawa** [comment]
Actually, could you post your phone and email?  We will need that in order to contact you if you win.

**Comment by crazydays** [comment]
616-607-4571 / daya@crazydays.org

**Comment by crazydays** [comment]
@mnishizawa - Added a solution to challenge 3.

**Comment by mnishizawa** [comment]
Challenge 3 verified.  You now have 6 total entries.  Thanks for your submission and best of luck!

**Pull request closed without merging**
